# [Create a Blog]

# POST http://localhost:8000/blogs
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg

# {
#     "title": "How are you doing?",
#     "content": ["I am doing well", "How about you?"],
#     "description": "Helpful for SEO",
#     "tags": ["hello", "world"],
#     "banner": "https://medium-blog-bucket.s3.eu-north-1.amazonaws.com/0hvj2JE5fQsUqjAm4U24h-1723454833846.jpeg"
# }

# [Login]

# POST http://localhost:8000/auth/sign-in
# Content-Type: application/json

# {
#     "email": "kimoomar@hotmail.com",
#     "password": "Kemo123123123"
# }

# [Get all blogs with Request Query features]

# GET http://localhost:8000/blogs?fields=-title&sort=title&limit=2&page=2&draft=true
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg

# [Get a Specific Blog]

# GET http://localhost:8000/blogs/66ba150911097ab52d37407e
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg

# [Update a Blog]

# PATCH http://localhost:8000/blogs/66ba150911097ab52d37407e
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg

# {
#     "title": "G"
# }

# [Delete a Blog]

# DELETE http://localhost:8000/blogs/66bb52f4effcd59fd0fa2df8
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg

# [Get Blogs]

# GET http://localhost:8000/blogs
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg


# [Latest Blogs]

# GET http://localhost:8000/blogs/latest?search=Git
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg

# Tredning Blogs

# GET http://localhost:8000/blogs/trending
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg

# [Get Blogs by Tag]
# GET http://localhost:8000/blogs/latest?page=2
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg

# [Search]
# GET http://localhost:8000/search?q=m&page=3
# Content-Type: application/json
# # Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjQ3NWNmMWRiMTM2YjcyOWQ0Nzc5MyIsImlhdCI6MTcyMzQ2MTgyMCwiZXhwIjoxNzIzNjM0NjIwfQ.tT8jt6ck1JuowCqychMOd-fY_ogvhTCsbc0RoUYlswg

# [Get user by id]
# GET http://localhost:8000/users/john1723807192060
# Content-Type: application/json

# [Get Blog by blog_id]
# GET http://localhost:8000/blogs/blog/comic-funny-frsjit1n8nzodkz_tcqqw
# Content-Type: application/json

# [Like]
# PATCH http://localhost:8000/blogs/like/66c31eef6c26e8dcb26e075d
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmYzNWU4NDIxMmRhNTYwMjk5OGMyYSIsImlhdCI6MTcyMzk3NzIwMCwiZXhwIjoxNzI0MTUwMDAwfQ.7f5XO5WO4YfRmTy8zww7YLprAUXSn4RtkVOfFQ_gWB8


# [Dislike]
# PATCH http://localhost:8000/blogs/dislike/66c31eef6c26e8dcb26e075d
# Content-Type: application/json
# Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmYzNWU4NDIxMmRhNTYwMjk5OGMyYSIsImlhdCI6MTcyMzk3NzIwMCwiZXhwIjoxNzI0MTUwMDAwfQ.7f5XO5WO4YfRmTy8zww7YLprAUXSn4RtkVOfFQ_gWB8

# [Create a Comment]
# POST http://localhost:8000/comments/66c48d11ffb0db479791dd4a
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzQ4Yzc1ZmZiMGRiNDc5NzkxZGQ0MyIsImlhdCI6MTcyNDE1OTI4NSwiZXhwIjoxNzI0MzMyMDg1fQ.CbRnfvN2bKyvKUek5kpG5CM-tZNPPaFuS4Aa5ul6KtE

# {
#     "content": "I am doing well"
# }

# [Create a Reply]
# POST http://localhost:8000/comments/66c5c241fd4dd694cee4ca85/replies
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzQ4Yzc1ZmZiMGRiNDc5NzkxZGQ0MyIsImlhdCI6MTcyNDE1OTI4NSwiZXhwIjoxNzI0MzMyMDg1fQ.CbRnfvN2bKyvKUek5kpG5CM-tZNPPaFuS4Aa5ul6KtE

# {
#     "content": "I am replying to a reply the reply well too"
# }


# [Get Comments]
# GET http://localhost:8000/comments/66c48d11ffb0db479791dd4a?page=2
# Content-Type: application/json

# [Get Replies]
# GET http://localhost:8000/comments/66c4fbb321b1ad291988b27f/replies
# Content-Type: application/json



# Like
# POST http://localhost:8000/comments/66c86cbf48470fb6c64f1e97/like
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzQ4Yzc1ZmZiMGRiNDc5NzkxZGQ0MyIsImlhdCI6MTcyNDQxMDI2NSwiZXhwIjoxNzI0NTgzMDY1fQ.fM87EJRfXBOJiSmraRWaB9wNtv9gTWwCkjY2KUMZV1k


# [Sign up]
# POST http://localhost:8000/auth/sign-up
# Content-Type: application/json

# {
#     "fullname": "AnanymouZ",
#     "email": "kimoomar009@gmail.com",
#     "password": "KimoOmar112233"
# }

# [Change Password]

# POST http://localhost:8000/auth/change-password
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Y2M4NGE1YmVkNWQwNzk4NWE0YjZkZiIsImlhdCI6MTcyNDY4MDc3NywiZXhwIjoxNzI0ODUzNTc3fQ.8OUxBIW5WyMk3FBFR-9PPKmyfL37AiLZxn1mbtVzgYc

# {
#     "current-password": "KimoOmar112233",
#     "new-password": "Kemo"
# }

# POST http://localhost:8000/auth/sign-in
# Content-Type: application/json

# {
#     "email": "kimoomar009@gmail.com",
#     "password":"KimoOmar112233"
# }

# [Get User Profile]
# GET http://localhost:8000/auth/profile
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGFhYjk0MDM4ZWMzMmM2MzRmODEyYyIsImlhdCI6MTcyNTY0NjcyMSwiZXhwIjoxNzI1ODE5NTIxfQ.hSU5hRAvw2UrwU5lMmyjGBeSyPJAdJeo7IhxDzceywQ



# GET http://localhost:8000/notifications/status
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Y2RiNjY4MmRhNWU4NmM1Nzk5OTJkOSIsImlhdCI6MTcyNTU2NDI1NSwiZXhwIjoxNzI1NzM3MDU1fQ.PRZ9bZ88f5JUguFGc7uRpCOoar5dhgWJrN1r5Hk-lWM

# GET http://localhost:8000/notifications
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Y2M4OWIyYmVkNWQwNzk4NWE0YjgxYyIsImlhdCI6MTcyNTYxMzIyNSwiZXhwIjoxNzI1Nzg2MDI1fQ.LfMaKW3bl7zS5ioB6V73X2fh6BA85-W2B_ZvFcmyKbU

GET http://localhost:8000/blogs/dashboard?page=1&draft=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGFhYjk0MDM4ZWMzMmM2MzRmODEyYyIsImlhdCI6MTcyNTcwNTExMCwiZXhwIjoxNzI1ODc3OTEwfQ.VBnMyPDi9bX4cKqyh9ZE8w0d7sNTdnl-by3mPfxDumM

